<div id="register">
	<form method="post" action="fonctions/inscription.php" id="inscription">
		<h3>Inscription</h3>
		<label for="name">Nom</label>
			<input type="text" class="formulaire" name="name" id="name" size="30" placeholder="---- nom ----" required/></input>
		<label for="firstname">Prenom</label>
			<input type="text" class="formulaire" name="firstname" id="firstname" size="30" placeholder="---- prenom ----" required></input>
		<label for="pseudo">Pseudo</label>
			<input type="text" class="formulaire" name="pseudo" id="pseudo" size="30" placeholder="---- pseudo ----" required></input>
		<label for="password">Password</label>
			<input type="password" class="formulaire" name="password" id="password" size="30" placeholder="---- password ----" required></input>
		<label for="departement">Departement</label>
			<input type="text" class="formulaire" name="departement" id="departement" size="30" placeholder="---- departement ----" required></input>
		<label for="ville">Ville</label>
			<input type="text" class="formulaire" name="ville" id="ville" size="30" placeholder="---- ville ----" required></input>
		<label for="mail">Email</label>
			<input type="text" class="formulaire" name="mail" id="mail" size="30" placeholder="---- email ----" required></input>
		<label for="birthday">Birthday</label>
			<input type="date" class="formulaire" name="birthday" id="birthday" size="30" placeholder="---- birthday ----" required></input>
		<div id="sex">
			<label for="sexe">Sexe</label>
				<input type="radio" class="formulaire" name="sexe" id="sexeH" size="30" placeholder="H" value="1">H</input>
				<input type="radio" class="formulaire" name="sexe" id="sexeF" size="30" placeholder="F" value="2">F</input>
		</div>
		<input id="valid" type="submit" value="Valider" class="valider" />
		<a href="form_login.phtml">Deja inscrit ? Connecte toi !</a>
	</form>
</div>