
<div id="login">
	<form method="post" action="fonctions/login.php" id="inscription">
		<h4>Login</h4>
		<label for="pseudo">Pseudo</label>
			<input type="text" class="formulaire" name="pseudo" id="pseudo" size="30" placeholder="---- pseudo ----" required></input>
		<label for="password">Password</label>
			<input type="password" class="formulaire" name="password" id="password" size="30" placeholder="---- password ----" required></input>
		<input id="valid" type="submit" value="Valider" class="valider" />
		<a href="form_register.phtml">Pas encore inscrit ? Aller go !</a>
	</form>
</div>
<?php include 'footer.phtml';?>