
<div id="login">
	<form method="post" action="fonctions/login.php" id="inscription">
		<h4>Login</h4>
		<label for="mail">Email</label>
			<input type="email" class="formulaire" name="mail" id="mail" size="30" placeholder="---- mail ----" required></input>
		<label for="password">Password</label>
			<input type="password" class="formulaire" name="password" id="password" size="30" placeholder="---- password ----" required></input>
		<input id="valid" type="submit" value="Valider" name="Connexion" class="valider" />
		<a href="form_register.phtml">Pas encore inscrit ? Aller go !</a>
	</form>
</div>